### ISSUE TITLE
Strange return from data on analysis portion of FCQ

### ISSUE THREAD

**Issue by pillig** [bigdatahci2015/forum#16]
I decided to begin my question for Friday today and ran into an error where whatever I returned ended up being [object Object]. I tried several different functions but kept getting the same thing. Then I decided to just return data itself and got this.

![screenshot from 2015-09-16 21 39 09](https://cloud.githubusercontent.com/assets/13927102/9924369/03740786-5cbc-11e5-9fdb-c240043d61e4.png)

Any idea why this is happening? The warmup from class still grabs the data fine, so I'm not convinced it has anything to do with the .json.

Thanks

**Comment by doubleshow** [comment]
You need to use the special `json` filter like this

{ foo | json }

in order to display the data in a nice format. 

If you only do 

{ foo }

you may get [object Object]

Please confirm if this helps.

**Comment by pillig** [comment]
Thank you,  that ended up working.
