### ISSUE TITLE
Extracting Instructor Name when using _.mapValues

### ISSUE THREAD

**Issue by KevinKGifford** [bigdatahci2015/forum#18]
I have been struggling with extracting the name of the course instructors 'Instructors', which is an array, when using the _.mapValues() function following the typical _.groupBy(data, ....) object generation.  Non-array values extract easily/as expected.  Can anyone point me to / hint at what I need to because I seem to be making this much more difficult than I'd expect it to be?

**Comment by karisantos** [comment]
Hi Kevin - I use _.map() when I have an array.
In the last problem of the warm up I ended up using filter/where
Hope that is enough of a hint.
Kari

**Comment by KevinKGifford** [comment]
Hi Kari - thanks for the reply.  I can extract the 'Instructor" name
properly when using _.map (via _.pluck) ala the final warm-up exercise.
When I attempt to do the same operation inside of _.mapValues it fails and
I'm trying to understand why.  In my case, I want to return a key-value
pair of 'AvgInstructor' (key) and "Instructors' (value which is a string)
so I can output in a table (to show which Instructors have low Instructor
ratings).

So thanks - you do what I tried as well, I just need to be able to perform
the same "logical" operation when using _.mapValues and I just haven't
figured out how to make it work.
Thanks again for the kind reply - much appreciated.

Kevin

**Comment by KevinKGifford** [comment]
I figured out how to do this with assistance from Karen Blakemore (thanks Karen!!).  I personally found this to be sticky so I'll post to the group in the case that it may help somebody.  For the data set given I wanted to extract the names of the Instructors which was a key-value array (see the data slice in fcq/index.md.  To pull out names of the course instructors the solution (Karen/I) utilized was:

return _.mapValues(groups, function(d) {
    return _.pluck(_.flatten(_.pluck(d, 'Instructors')), 'name')
})

Hope this helps somebody.

Kevin
