### ISSUE TITLE
Tried to push and could not upload birdstrikes.json

### ISSUE THREAD

**Issue by bdmckean** [bigdatahci2015/forum#24]
remote: error: File _book/hackathons/birdstrikes/birdstrikes.json is 135.64 MB; this exceeds GitHub's file size limit of 100.00 MB

**Comment by karisantos** [comment]
I just removed the file from the dir (and the _book dir) and pushed the rest. I thought about adding the file to .gitignore , but I wasn;t sure if that was the right thing to do. Any suggestion from more git-savvy people?

**Comment by calebhsu** [comment]
@karisantos If you remove the file and try to deploy it, wouldn't the Lodash not work on the github.io page? *Our group is also running into the same issue

**Comment by karisantos** [comment]
This is my order and github.io looks good:
gitbook build
remove large json files from dir and _book dir
commit and sync on github app
git subtree push --prefix _book origin gh-pages
check github https://github.com/karisantos/book and http://karisantos.github.io/book
put json back in book (don’t worry about _book)

**Comment by bdmckean** [comment]
I tried to follow your process and have removed all the large json files after the "gitbook build" but I get the same error message even though the files are not there.

**Comment by anbe6083** [comment]
I'm also getting the same error, even after following kari's instructions

**Comment by KevinKGifford** [comment]
Hey guys (co-bri, anbe6083): A suggestion is to trim your JSON file to just
the data (columns) you need.  Google csvkit, download and install csvkit,
then look at the commands in2csv and csvcut.  See:
https://csvkit.readthedocs.org/en/0.9.1/ - this should take you about 15
minutes, FYI, then you'll be set.

Hope this helps - your code should run just fine on the pared down JSON
file.

Kevin

**Comment by anbe6083** [comment]
Ok, I tried csvcut using this command 
    csvcut -c 17,33,7,13,2,26,18 birdstrikes.csv
it parses the data, but doesn't extract those columns. Any ideas?

**Comment by KevinKGifford** [comment]
To get the column names: csvcut -n birdstrike.csv

To cut the column data out (I use my example): csvcut -c 'Airport:
Name','Aircraft: Airline/Operator','Aircraft: Make/Model','Effect:
Indicated Damage','When: Phase of flight','Feet above ground','Conditions:
Sky','Cost: Total $' birdstrike.csv | csvjson --indent 4 > birdstrike.json

Hope this helps.

Kevin

**Comment by bdmckean** [comment]
I am still unable to figure out how to make git forget about those large files.  No matter what I try I keep getting the same set of errors like this:
remote: error: File _book/hackathons/birdstrikes/birdstrikes.json is 135.64 MB; this exceeds GitHub's file size limit of 100.00 MB
Even if the files have been deleted from my directories.

**Comment by bdmckean** [comment]
Finally got my changes into git
1) Saved all my working files in another directory (manually, not using git)
2) git reset --hard @{u}
(found this here http://sethrobertson.github.io/GitFixUm/fixup.html#discard_all_unpushed)
(This took out all my unpushed changes)
3) put files back that I had saved
4) followed karisantos instructions above
Thanks for all the help and advice!

**Comment by anbe6083** [comment]
I tried what you did, when I try to push book I get this error:

 ! [rejected]        cd06894d7472387c2a5c3a6056d13f9f274e7737 -> gh-pages (non-fast-forward)
error: failed to push some refs to 'https://github.com/anbe6083/book.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by calebhsu** [comment]
@anbe6083 I think I finally figured out how to deploy to gh-pages if you're getting the fastforward error.
First run `gitbook build`, then

`git checkout master` makes sure you're on the master branch
`git subtree split --prefix _book -b gh-pages` creates a local version of gh-pages with splitted _book folder
`git push -f origin gh-pages:gh-pages` force push local gh-pages to remote gh-pages
`git branch -D gh-pages` deletes local gh-pages

Source: http://www.damian.oquanta.info/posts/one-line-deployment-of-your-site-to-gh-pages.html

Hopefully that works!

**Comment by anbe6083** [comment]
I think I love you, that finally worked. Thanks so much!
