### ISSUE TITLE
Week 6 update breaks working ability

### ISSUE THREAD

**Issue by KevinKGifford** [bigdatahci2015/forum#28]
I did the standard update process, including nom update, and upon restarting "gitbook serve" get the following error:

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book> gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: load plugin gitbook-plugin-bigdata ....OK 
info: load plugin gitbook-plugin-toggle-chapters ....OK 
info: load plugin gitbook-plugin-livereload ....OK 
info: >> 3 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 
Received query: {"n":"com.evernote"}
Error: Failed to connect to MongoDB at: mongodb://localhost:27017/apps connect ECONNREFUSED

Template render error: (/Users/gifford/4830/book/learning/week6/mongodb-drills.md)
  TypeError: Cannot set property 'id' of undefined (In file 'learning/week6/mongodb-drills.md')
gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book>

**Comment by kalharbi** [comment]
@KevinKGifford Sorry, about that error. Week 6 module requires running a local instance of MongoDB. Please follow the setup instructions at 
https://github.com/bigdatahci2015/book/blob/master/learning/week6/mongodb-setup.md
and then you can run the usual gitbook serve.
