### ISSUE TITLE
Help with Gitbook Serving

### ISSUE THREAD

**Issue by DomoYeti** [bigdatahci2015/forum#39]
When I use my gitbook serve function in terminal on Ubuntu, I get this error:

Invalid version or tag '2.5.0-beta.4', see available using 'gitbook versions:available'

I just pulled the Week 8 stuff and this started happening, how do I fix this?

**Comment by doubleshow** [comment]
What did you get when you run gitbook versions:available, did you get what I got:

![2__bash](https://cloud.githubusercontent.com/assets/129562/10500907/7865f8e0-7299-11e5-909c-28a014f3a2aa.png)

**Comment by DomoYeti** [comment]
Mine is a bit different.

Available GitBook Versions:

```
 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0
```

Tags:

```
 latest : 2.4.3
```

**Comment by doubleshow** [comment]
try

```
 npm update -g gitbook-cli
```

see if you will get more gitbook versions afterward
you may need to `sudo`

**Comment by DomoYeti** [comment]
That command worked, I just used gitbook serve again and it installed a new version of gitbook. Thanks for your help.
