### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by anbe6083** [bigdatahci2015/forum#41]
Ever since updating gitbook, I started getting this error. It's been catching on two lines: 

`items = _.map(lines, JSON.parse)` 

`var template = _.template(tplString)`

both in ui.html . Any idea how to fix this?

**Comment by pillig** [comment]
Had the same problem until I did npm install and gitbook install. The '_ is not defined' is actually catching in a reference to the "bigdata" plugin.

**Comment by anbe6083** [comment]
That did it, I appreciate the help
