### ISSUE TITLE
Url for graph website for this week's hackathon

### ISSUE THREAD

**Issue by pillig** [bigdatahci2015/forum#63]
Does anyone have the url that was displayed on the TV during today's hackathon for the n-graphs? 

Thanks

**Comment by kjblakemore** [comment]
Not sure if this is what you are looking for, but Danielle Sazfer, showed us two urls at the end of her presentation.  These were:
Text DNA: http://vep.cs.wisc.edu/TextDNA/app/templates/viewer.html
Google n-grams viewer: https://books.google.com/ngrams

**Comment by pillig** [comment]
Thanks a lot, those are them.
